algoritmo "Refazer_exercicio_contagem_inteligente"
var
   primeiro_numero, segundo_numero, contador: inteiro
inicio
      contador <- 0
      Escreva ("Digite o primeiro número: " )
      Leia (primeiro_numero)
      Escreva ("Digite o segundo número: ")
      Leia(segundo_numero)
      Enquanto (contador <= primeiro_numero) faça
               contador + 1
               Escreva (contador, ".. ")
      FimEnquanto
      


fimalgoritmo