algoritmo "SomaValoresFuncoes"
var
   primeiro_valor, segundo_valor, s: inteiro
Funcao soma (x, y: inteiro): inteiro
inicio
      Retorne x + y
FimFuncao
inicio
      Escreva ("Digite o primeiro valor: ")
      Leia (primeiro_valor)
      Escreva ("Digite o segundo valor: ")
      Leia (segundo_valor)
      s <- soma (primeiro_valor, segundo_valor)
      Escreval ("A soma entre ", primeiro_valor, " e ", segundo_valor, " é igual ", s)
fimalgoritmo